package de.fitnesscoach.domain.fitness;

import static org.junit.Assert.*;import java.time.LocalDate;import java.util.*;import org.junit.Test;import de.fitnesscoach.data.entity.*;
public class FitnessIntelligenceTest {
 @Test public void baselineIgnoresMissingAndSuspect(){List<DailyHealthEntity>d=new ArrayList<>();for(int i=0;i<7;i++){DailyHealthEntity x=new DailyHealthEntity();x.date=LocalDate.now().minusDays(i);x.sleepMinutes=i==0?null:420+i;x.sleepQuality=i==1?DomainEnums.DataQuality.SUSPECT:DomainEnums.DataQuality.AVAILABLE;d.add(x);}BaselineEntity b=new BaselineCalculator().calculate("sleepMinutes",7,d);assertEquals(5,b.sampleCount);assertNotNull(b.value);assertEquals(DomainEnums.Confidence.MEDIUM,b.confidence);}
 @Test public void trainingLoadUsesRpeAndRatio(){WorkoutEntity w=new WorkoutEntity();w.durationMinutes=60;w.rpe=5;TrainingLoadCalculator c=new TrainingLoadCalculator();assertEquals(60,c.workoutLoad(w),.001);assertEquals(2,c.acuteChronicRatio(120,240),.001);}
 @Test public void recoveryDoesNotInventMissingMeasurements(){DailyHealthEntity h=new DailyHealthEntity();h.date=LocalDate.now();BaselineEntity s=new BaselineEntity();s.value=480d;RecoveryEntity r=new RecoveryCalculator().calculate(h.date,h,s,null,1,null);assertNull(r.sleepComponent);assertNull(r.restingHeartRateComponent);assertNotNull(r.score);assertEquals(DomainEnums.Confidence.INSUFFICIENT,r.confidence);assertEquals(DomainEnums.RecoveryRecommendation.UNKNOWN,r.recommendation);}
 @Test public void recoveryUsesObjectiveAndSubjectiveSignals(){DailyHealthEntity h=new DailyHealthEntity();h.date=LocalDate.now();h.sleepMinutes=480;h.restingHeartRate=50d;BaselineEntity s=new BaselineEntity();s.value=480d;BaselineEntity hr=new BaselineEntity();hr.value=50d;CheckInEntity c=new CheckInEntity();c.energy=5;c.motivation=4;c.muscleFatigue=1;c.stress=2;RecoveryEntity r=new RecoveryCalculator().calculate(h.date,h,s,hr,.9,c);assertTrue(r.score>=80);assertEquals(DomainEnums.Confidence.HIGH,r.confidence);}
}
