package de.fitnesscoach.domain.fitness;

import static org.junit.Assert.*;import java.time.LocalDate;import java.util.*;import org.junit.Test;import de.fitnesscoach.data.entity.*;
public class FitnessIntelligenceTest {
 @Test public void baselineIgnoresMissingAndSuspect(){List<DailyHealthEntity>d=new ArrayList<>();for(int i=0;i<7;i++){DailyHealthEntity x=new DailyHealthEntity();x.date=LocalDate.now().minusDays(i);x.sleepMinutes=i==0?null:420+i;x.sleepQuality=i==1?DomainEnums.DataQuality.SUSPECT:DomainEnums.DataQuality.AVAILABLE;d.add(x);}BaselineEntity b=new BaselineCalculator().calculate("sleepMinutes",7,d);assertEquals(5,b.sampleCount);assertEquals(DomainEnums.Confidence.MEDIUM,b.confidence);}
 @Test public void baselineMinimumSamplesIsConfigurable(){BaselineCalculator c=new BaselineCalculator(new BaselineCalculator.Config(5,.75,.5));assertEquals(DomainEnums.Confidence.INSUFFICIENT,c.calculateValues("trainingLoad",7,Arrays.asList(1d,2d,3d,4d)).confidence);}
 @Test public void trainingLoadUsesSpecifiedRpe(){WorkoutEntity w=new WorkoutEntity();w.durationMinutes=60;w.rpe=5;assertEquals(300,new DefaultTrainingLoadCalculator().workoutLoad(w),.001);}
 @Test public void trainingLoadFallsBackByWorkoutType(){WorkoutEntity w=new WorkoutEntity();w.durationMinutes=30;w.workoutType=DomainEnums.WorkoutType.INTERVAL;assertEquals(240,new DefaultTrainingLoadCalculator().workoutLoad(w),.001);}
 @Test public void missingChronicLoadIsMissingNotZero(){assertNull(new DefaultTrainingLoadCalculator().acuteChronicRatio(0,0));}
 @Test public void allRecoveryDataMissingIsUnknown(){RecoveryEntity r=new RecoveryCalculator().calculate(LocalDate.now(),null,null,null,null,null);assertNull(r.score);assertEquals(DomainEnums.Confidence.INSUFFICIENT,r.confidence);assertEquals(DomainEnums.RecoveryRecommendation.UNKNOWN,r.recommendation);}
 @Test public void recoveryNormalizesAvailableWeights(){DailyHealthEntity h=new DailyHealthEntity();h.date=LocalDate.now();h.sleepMinutes=480;h.sleepQuality=DomainEnums.DataQuality.AVAILABLE;BaselineEntity s=new BaselineEntity();s.value=480d;RecoveryEntity r=new RecoveryCalculator().calculate(h.date,h,s,null,null,null);assertEquals(Integer.valueOf(100),r.score);}
 @Test public void recoveryThresholdsCoverAllCategories(){RecoveryCalculator c=new RecoveryCalculator(new RecoveryCalculator.Config(1,0,0,0,80,65,45,25));assertEquals(DomainEnums.RecoveryRecommendation.FULL,recommendationForSleep(c,80));assertEquals(DomainEnums.RecoveryRecommendation.NORMAL,recommendationForSleep(c,70));assertEquals(DomainEnums.RecoveryRecommendation.REDUCED,recommendationForSleep(c,50));assertEquals(DomainEnums.RecoveryRecommendation.RECOVERY_ONLY,recommendationForSleep(c,30));assertEquals(DomainEnums.RecoveryRecommendation.REST,recommendationForSleep(c,10));}
 private static DomainEnums.RecoveryRecommendation recommendationForSleep(RecoveryCalculator c,int score){DailyHealthEntity h=new DailyHealthEntity();h.sleepMinutes=(int)Math.round(480*score/100d);h.sleepQuality=DomainEnums.DataQuality.AVAILABLE;h.restingHeartRate=50d;h.restingHeartRateQuality=DomainEnums.DataQuality.AVAILABLE;BaselineEntity s=new BaselineEntity();s.value=480d;BaselineEntity hr=new BaselineEntity();hr.value=50d;CheckInEntity x=new CheckInEntity();x.energy=3;x.motivation=3;x.muscleFatigue=3;x.stress=3;RecoveryEntity r=c.calculate(LocalDate.now(),h,s,hr,1d,x);assertEquals(Integer.valueOf(score),r.score);return r.recommendation;}
}
