package de.fitnesscoach.ui.plan;

import java.time.*;import java.util.*;import de.fitnesscoach.data.entity.*;import de.fitnesscoach.data.repository.FitnessCoachRepository;import de.fitnesscoach.domain.plan.*;import de.fitnesscoach.ui.GermanLabels;

public final class PlanDiagnosticsMapper {
 private PlanDiagnosticsMapper() {}
 public static PlanDiagnosticsUiState map(LocalDate weekStart,FitnessCoachRepository repo){LocalDate weekEnd=weekStart.plusDays(6);UserProfileEntity profile=repo.getProfile();GoalEntity goal=repo.getActiveGoal();List<TrainingAvailabilityEntity> availability=repo.getAvailability();BaselineEntity loadBaseline=repo.getBaseline("trainingLoad",28);List<PlannedWorkoutEntity> persistedPlan=repo.getPlannedWorkouts(weekStart,weekEnd);List<WorkoutEntity> actual=repo.getWorkouts();TrainingPlanGenerator.Result evaluated=new TrainingPlanGenerator().generate(weekStart,profile,goal,availability,loadBaseline);StringBuilder b=new StringBuilder();b.append("EPIC 04 TRAININGSPLAN-DIAGNOSE\nWoche: ").append(weekStart).append(" – ").append(weekEnd).append("\n\n");
 b.append("1. EINGABEDATEN\n");b.append("Fitnesslevel: ").append(profile==null||profile.fitnessLevel==null?"fehlt":GermanLabels.fitness(profile.fitnessLevel)).append('\n');if(goal==null)b.append("Primärziel: fehlt\n");else b.append("Primärziel: ").append(GermanLabels.goalType(goal.type)).append(" | ").append(n(goal.title)).append(" | Zielwert=").append(goal.targetValue==null?"fehlt":goal.targetValue+" "+n(goal.targetUnit)).append(" | Datum=").append(goal.targetDate==null?"fehlt":goal.targetDate).append('\n');b.append("Trainingslast-Basiswert 28 Tage: ");if(loadBaseline==null||loadBaseline.value==null)b.append("fehlt / unzureichend\n");else b.append(fmt(loadBaseline.value)).append(" | Stichproben=").append(loadBaseline.sampleCount).append(" | Vertrauen=").append(GermanLabels.confidence(loadBaseline.confidence)).append('\n');b.append("Verfügbarkeit:\n");if(availability==null||availability.isEmpty())b.append("  fehlt\n");else for(TrainingAvailabilityEntity a:availability){b.append("  ").append(GermanLabels.day(DayOfWeek.of(a.dayOfWeek))).append(": ").append(a.available?"verfügbar":"nicht verfügbar").append(a.available?" | max. "+(a.maxDurationMinutes==null?"fehlt":a.maxDurationMinutes+" Min."):"").append(a.preferredTime==null?"":" | bevorzugt="+a.preferredTime).append('\n');}
 b.append("\n2. AUSWERTUNG DES PRODUKTIVEN GENERATORS\n");b.append("Generator-Vertrauen: ").append(GermanLabels.confidence(evaluated.confidence)).append('\n');b.append("Ausgewählte Einheiten: ").append(evaluated.workouts.size()).append('\n');if(evaluated.workouts.isEmpty())b.append("Keine Einheiten erzeugt. Typische Ursache: kein verfügbarer Tag mit mindestens 20 Minuten.\n");for(PlannedWorkoutEntity p:evaluated.workouts)appendWorkout(b,"  ausgewertet",p);if(loadBaseline==null||loadBaseline.confidence==null||loadBaseline.confidence==DomainEnums.Confidence.INSUFFICIENT)b.append("Konservativer Fallback: JA — Trainingslast-Basis fehlt/ist unzureichend; Generator meldet niedriges Vertrauen.\n");else b.append("Konservativer Fallback: kein Fallback wegen Basiswert-Vertrauen erforderlich.\n");b.append("Intensitäts-Nachbarschaftsregel: aufeinanderfolgende intensive Einheiten werden bei Bedarf auf locker reduziert.\n");b.append("Dauerbegrenzung: jede Einheit wird auf die maximale Dauer des gewählten Tages begrenzt.\n");
 b.append("\n3. PERSISTIERTER PLANZUSTAND\n");if(persistedPlan==null||persistedPlan.isEmpty())b.append("Keine gespeicherten Einheiten für die ausgewählte Woche.\n");else for(PlannedWorkoutEntity p:persistedPlan)appendWorkout(b,"  gespeichert",p);
 b.append("\n4. AUSWERTUNG DER ERHOLUNGSANPASSUNG\n");if(persistedPlan==null||persistedPlan.isEmpty())b.append("Kein geplantes Training zur Auswertung vorhanden.\n");else{DefaultPlanAdaptationPolicy policy=new DefaultPlanAdaptationPolicy();for(int i=0;i<persistedPlan.size();i++){PlannedWorkoutEntity current=persistedPlan.get(i);PlannedWorkoutEntity previous=i>0?persistedPlan.get(i-1):null;PlannedWorkoutEntity next=i+1<persistedPlan.size()?persistedPlan.get(i+1):null;RecoveryEntity recovery=repo.getRecovery(current.date);DomainEnums.RecoveryRecommendation rec=recovery==null||recovery.recommendation==null?DomainEnums.RecoveryRecommendation.UNKNOWN:recovery.recommendation;PlannedWorkoutEntity after=policy.adapt(current,rec,previous,next);b.append(current.date).append(" Empfehlung=").append(GermanLabels.recovery(rec)).append(" | vorheriges=").append(previous==null?"keins":GermanLabels.workout(previous.workoutType)).append(" | nächstes=").append(next==null?"keins":GermanLabels.workout(next.workoutType)).append('\n');b.append("  vorher: ").append(snapshot(current)).append('\n');b.append("  nachher: ").append(snapshot(after)).append('\n');b.append("  Aktion: ").append(after.status==DomainEnums.WorkoutStatus.ADAPTED?"Anpassung würde angewendet":"keine Anpassung").append('\n');}}
 b.append("\n5. MATCHING IMPORTIERTER TRAININGS\n");WorkoutMatcher matcher=new WorkoutMatcher();boolean anyActual=false;if(actual!=null)for(WorkoutEntity w:actual){if(w.startTime==null)continue;LocalDate d=w.startTime.atZone(ZoneId.systemDefault()).toLocalDate();if(d.isBefore(weekStart)||d.isAfter(weekEnd))continue;anyActual=true;WorkoutMatcher.Match match=matcher.best(w,persistedPlan==null?Collections.emptyList():persistedPlan);b.append(d).append(" tatsächliches Training id=").append(w.id).append(" | Sport=").append(GermanLabels.sport(w.sportType)).append(" | Typ=").append(GermanLabels.workout(w.workoutType)).append(" | Dauer=").append(v(w.durationMinutes)).append(" Min.").append(" | Distanz=").append(v(w.distanceKm)).append(" km\n").append("  bester Score=").append(fmt(match.score)).append(" | Vertrauen=").append(matchConfidence(match.confidence)).append(" | Kandidat=").append(match.planned==null?"keiner":match.planned.id).append(" | Auto-Match=").append(match.confidence==WorkoutMatcher.MatchConfidence.HIGH&&match.planned!=null?"JA":"NEIN").append(" | gespeicherte Verknüpfung=").append(w.plannedWorkoutId==null?"keine":w.plannedWorkoutId).append('\n');}if(!anyActual)b.append("Keine importierten Trainings in der ausgewählten Woche.\n");b.append("Das produktive Matching bewertet: gleicher Tag, kompatible Sportart, Dauer, Distanz und Trainingstyp. Niedriges Vertrauen wird nie automatisch zugeordnet.\n");
 b.append("\n6. COACHDECISION-AUDIT-TRAIL\n");List<CoachDecisionEntity> decisions=repo.getDecisions();boolean anyDecision=false;if(decisions!=null)for(CoachDecisionEntity d:decisions){if(!isPlanDecision(d))continue;anyDecision=true;b.append(d.timestamp==null?"Zeit unbekannt":d.timestamp).append(" | ").append(d.decisionType).append(" | Ziel=").append(d.targetEntityId).append(" | Quelle=").append(n(d.source)).append('\n').append("  Grund: ").append(n(d.reasonCode)).append(" — ").append(n(d.reasonText)).append('\n').append("  vorher: ").append(n(d.beforeJson)).append('\n').append("  nachher: ").append(n(d.afterJson)).append('\n');}if(!anyDecision)b.append("Noch keine planbezogenen CoachDecision-Einträge.\n");return new PlanDiagnosticsUiState(weekStart,b.toString().trim());}
 private static String matchConfidence(WorkoutMatcher.MatchConfidence c){if(c==null)return"Unbekannt";switch(c){case HIGH:return"Hoch";case MEDIUM:return"Mittel";case LOW:return"Niedrig";default:return c.name();}}
 private static boolean isPlanDecision(CoachDecisionEntity d){if(d==null||d.decisionType==null)return false;switch(d.decisionType){case CREATE_WORKOUT:case REDUCE_WORKOUT:case CANCEL_WORKOUT:case REPLACE_WORKOUT:return true;default:return false;}}
 private static void appendWorkout(StringBuilder b,String prefix,PlannedWorkoutEntity p){b.append(prefix).append(" id=").append(p.id).append(" | ").append(p.date).append(" | ").append(GermanLabels.sport(p.sportType)).append(" | ").append(GermanLabels.workout(p.workoutType)).append(" | Dauer=").append(v(p.plannedDurationMinutes)).append(" Min.").append(" | Distanz=").append(v(p.plannedDistanceKm)).append(" km").append(" | Puls=").append(v(p.targetHeartRateMin)).append("-").append(v(p.targetHeartRateMax)).append(" | Tempo=").append(v(p.targetPaceMinSecKm)).append("-").append(v(p.targetPaceMaxSecKm)).append(" | Status=").append(GermanLabels.workoutStatus(p.status)).append(" | v").append(p.version).append(" | Original=").append(p.originalWorkoutId==null?"keins":p.originalWorkoutId).append('\n').append("    ").append(n(p.title)).append(" — ").append(n(p.description)).append('\n');}
 private static String snapshot(PlannedWorkoutEntity p){return"Typ="+GermanLabels.workout(p.workoutType)+", Sport="+GermanLabels.sport(p.sportType)+", Dauer="+p.plannedDurationMinutes+", Status="+GermanLabels.workoutStatus(p.status)+", Version="+p.version;}private static String n(String s){return s==null||s.isBlank()?"fehlt":s;}private static String v(Object o){return o==null?"fehlt":String.valueOf(o);}private static String fmt(double d){return String.format(Locale.GERMANY,"%.2f",d);}
}
