package de.fitnesscoach.ui;

import android.os.Bundle;import android.view.View;import androidx.appcompat.app.AppCompatActivity;import java.time.LocalDate;import java.time.ZoneId;import java.util.*;import java.util.concurrent.*;import de.fitnesscoach.data.db.FitnessCoachDatabase;import de.fitnesscoach.data.entity.*;import de.fitnesscoach.data.repository.*;import de.fitnesscoach.databinding.ActivityWorkoutReviewBinding;import de.fitnesscoach.domain.fitness.FitnessIntelligenceService;

public class WorkoutReviewActivity extends AppCompatActivity {public static final String EXTRA_WORKOUT_ID="workout_id";private ActivityWorkoutReviewBinding binding;private final ExecutorService ex=Executors.newSingleThreadExecutor();private FitnessCoachRepository repo;private WorkoutEntity workout;private PlannedWorkoutEntity planned;
 @Override protected void onCreate(Bundle s){super.onCreate(s);binding=ActivityWorkoutReviewBinding.inflate(getLayoutInflater());setContentView(binding.getRoot());repo=new RoomFitnessCoachRepository(FitnessCoachDatabase.getInstance(this));long id=getIntent().getLongExtra(EXTRA_WORKOUT_ID,-1);binding.workoutReviewSave.setEnabled(false);binding.workoutReviewSkip.setOnClickListener(v->finish());binding.workoutReviewSave.setOnClickListener(v->save());ex.execute(()->load(id));}
 private void load(long id){for(WorkoutEntity w:repo.getWorkouts())if(w.id==id){workout=w;break;}if(workout!=null&&workout.plannedWorkoutId!=null&&workout.startTime!=null){LocalDate d=workout.startTime.atZone(ZoneId.systemDefault()).toLocalDate();List<PlannedWorkoutEntity> list=repo.getPlannedWorkouts(d,d);for(PlannedWorkoutEntity p:list)if(p.id==workout.plannedWorkoutId){planned=p;break;}}runOnUiThread(this::render);}
 private void render(){if(workout==null){binding.workoutReviewComparison.setText("Training nicht verfügbar.");return;}StringBuilder b=new StringBuilder();b.append("TATSÄCHLICH\nDauer: ").append(val(workout.durationMinutes," Min.")).append("\nDistanz: ").append(val(workout.distanceKm," km")).append("\nDurchschnittspuls: ").append(val(workout.averageHeartRate," bpm")).append("\nTempo: ").append(workout.averagePaceSecPerKm==null?"nicht verfügbar":pace(workout.averagePaceSecPerKm)+" /km").append("\n\nGEPLANT\n");if(planned==null)b.append("Kein passendes geplantes Training zugeordnet.");else b.append("Dauer: ").append(val(planned.plannedDurationMinutes," Min.")).append("\nDistanz: ").append(val(planned.plannedDistanceKm," km")).append("\nPulsziel: ").append(planned.targetHeartRateMin==null||planned.targetHeartRateMax==null?"nicht verfügbar":fmt(planned.targetHeartRateMin)+"–"+fmt(planned.targetHeartRateMax)+" bpm").append("\nTempoziel: ").append(planned.targetPaceMinSecKm==null||planned.targetPaceMaxSecKm==null?"nicht verfügbar":pace(planned.targetPaceMinSecKm)+"–"+pace(planned.targetPaceMaxSecKm)+" /km");binding.workoutReviewComparison.setText(b.toString());binding.workoutReviewRpe.setText(workout.rpe==null?"":String.valueOf(workout.rpe));binding.workoutReviewNote.setText(workout.reviewNote==null?"":workout.reviewNote);binding.workoutReviewSave.setEnabled(true);}
 private void save(){binding.workoutReviewError.setVisibility(View.GONE);String raw=binding.workoutReviewRpe.getText().toString().trim();Integer rpe=null;if(!raw.isEmpty()){try{rpe=Integer.valueOf(raw);}catch(Exception e){error("RPE muss eine Zahl von 1 bis 10 sein.");return;}if(rpe<1||rpe>10){error("RPE muss zwischen 1 und 10 liegen.");return;}}workout.rpe=rpe;String note=binding.workoutReviewNote.getText().toString().trim();workout.reviewNote=note.isEmpty()?null:note;binding.workoutReviewSave.setEnabled(false);ex.execute(()->{repo.updateWorkout(workout);if(workout.startTime!=null)new FitnessIntelligenceService(repo).refresh(workout.startTime.atZone(ZoneId.systemDefault()).toLocalDate());runOnUiThread(this::finish);});}
 private void error(String m){binding.workoutReviewError.setText(m);binding.workoutReviewError.setVisibility(View.VISIBLE);}private String val(Object v,String unit){return v==null?"nicht verfügbar":v+unit;}private String fmt(double v){return String.format(Locale.GERMANY,"%.1f",v);}private String pace(int s){return(s/60)+":"+String.format(Locale.ROOT,"%02d",s%60);}@Override protected void onDestroy(){super.onDestroy();ex.shutdownNow();}
}
