package de.fitnesscoach.ui.plan;

import static org.junit.Assert.assertTrue;import org.junit.Test;import java.time.*;import java.util.*;import de.fitnesscoach.data.entity.*;import de.fitnesscoach.data.repository.FitnessCoachRepository;

public class PlanDiagnosticsMapperTest {
 private static final LocalDate WEEK=LocalDate.of(2026,8,24);
 @Test public void sparseInputsAreVisible(){FakeRepo repo=new FakeRepo();String text=PlanDiagnosticsMapper.map(WEEK,repo).text;assertTrue(text.contains("Fitnesslevel: fehlt"));assertTrue(text.contains("Primärziel: fehlt"));assertTrue(text.contains("Trainingslast-Basiswert 28 Tage: fehlt / unzureichend"));assertTrue(text.contains("Keine gespeicherten Einheiten"));assertTrue(text.contains("Keine importierten Trainings"));}
 @Test public void generationAdaptationMatchingAndAuditAreVisible(){FakeRepo repo=new FakeRepo();repo.profile=new UserProfileEntity();repo.profile.fitnessLevel=DomainEnums.FitnessLevel.REGULAR;TrainingAvailabilityEntity a=new TrainingAvailabilityEntity();a.dayOfWeek=1;a.available=true;a.maxDurationMinutes=45;repo.availability.add(a);PlannedWorkoutEntity p=new PlannedWorkoutEntity();p.id=10;p.date=WEEK;p.sportType=DomainEnums.SportType.RUNNING;p.workoutType=DomainEnums.WorkoutType.EASY;p.plannedDurationMinutes=40;p.status=DomainEnums.WorkoutStatus.PLANNED;p.version=1;repo.planned.add(p);WorkoutEntity w=new WorkoutEntity();w.id=20;w.startTime=WEEK.atTime(8,0).atZone(ZoneId.systemDefault()).toInstant();w.sportType=DomainEnums.SportType.RUNNING;w.workoutType=DomainEnums.WorkoutType.EASY;w.durationMinutes=40;repo.workouts.add(w);RecoveryEntity r=new RecoveryEntity();r.date=WEEK;r.recommendation=DomainEnums.RecoveryRecommendation.REDUCED;repo.recovery=r;CoachDecisionEntity d=new CoachDecisionEntity();d.timestamp=Instant.parse("2026-08-24T09:00:00Z");d.decisionType=DomainEnums.CoachDecisionType.CREATE_WORKOUT;d.targetEntityId=10L;d.source="DETERMINISTIC_PLAN_ENGINE";d.reasonCode="INITIAL_PLAN";d.reasonText="test";d.afterJson="after";repo.decisions.add(d);String text=PlanDiagnosticsMapper.map(WEEK,repo).text;assertTrue(text.contains("Ausgewählte Einheiten: 1"));assertTrue(text.contains("Empfehlung=Reduziert trainieren"));assertTrue(text.contains("Vertrauen=Hoch"));assertTrue(text.contains("Auto-Match=JA"));assertTrue(text.contains("CREATE_WORKOUT"));}
 private static final class FakeRepo implements FitnessCoachRepository{UserProfileEntity profile;RecoveryEntity recovery;final List<TrainingAvailabilityEntity> availability=new ArrayList<>();final List<PlannedWorkoutEntity> planned=new ArrayList<>();final List<WorkoutEntity> workouts=new ArrayList<>();final List<CoachDecisionEntity> decisions=new ArrayList<>();public UserProfileEntity getProfile(){return profile;}public void saveProfile(UserProfileEntity p){}public List<TrainingAvailabilityEntity> getAvailability(){return availability;}public void saveAvailability(TrainingAvailabilityEntity a){}public GoalEntity getActiveGoal(){return null;}public long insertGoal(GoalEntity g){return 0;}public DailyHealthEntity getDailyHealth(LocalDate d){return null;}public void saveDailyHealth(DailyHealthEntity h){}public List<WorkoutEntity> getWorkouts(){return workouts;}public long insertWorkout(WorkoutEntity w){return 0;}public void updateWorkout(WorkoutEntity w){}public List<PlannedWorkoutEntity> getPlannedWorkouts(LocalDate f,LocalDate t){return planned;}public PlannedWorkoutEntity getPlannedWorkout(long id){for(PlannedWorkoutEntity p:planned)if(p.id==id)return p;return null;}public long insertPlannedWorkout(PlannedWorkoutEntity w){return 0;}public void updatePlannedWorkout(PlannedWorkoutEntity w){}public CheckInEntity getCheckIn(LocalDate d){return null;}public void saveCheckIn(CheckInEntity c){}public BaselineEntity getBaseline(String m,int w){return null;}public void saveBaseline(BaselineEntity b){}public RecoveryEntity getRecovery(LocalDate d){return recovery!=null&&d.equals(recovery.date)?recovery:null;}public void saveRecovery(RecoveryEntity r){}public List<CoachMemoryEntity> getActiveMemories(){return Collections.emptyList();}public long insertMemory(CoachMemoryEntity m){return 0;}public List<CoachDecisionEntity> getDecisions(){return decisions;}public long insertDecision(CoachDecisionEntity d){return 0;}}
}
