package de.fitnesscoach.ui.today;

import java.time.*;import java.util.*;import de.fitnesscoach.data.entity.*;import de.fitnesscoach.data.repository.FitnessCoachRepository;import de.fitnesscoach.domain.fitness.*;

public final class FitnessDiagnosticsMapper {
 private FitnessDiagnosticsMapper(){}
 public static FitnessDiagnosticsUiState map(LocalDate date,FitnessCoachRepository repo){DailyHealthEntity h=repo.getDailyHealth(date);CheckInEntity c=repo.getCheckIn(date);RecoveryEntity r=repo.getRecovery(date);List<WorkoutEntity> all=repo.getWorkouts();TrainingLoadCalculator calc=new DefaultTrainingLoadCalculator();List<WorkoutEntity> day=between(all,date,date);List<WorkoutEntity> w7=between(all,date.minusDays(6),date),w28=between(all,date.minusDays(27),date);double l7=calc.total(w7),l28=calc.total(w28);Double ratio=calc.acuteChronicRatio(l7,l28);StringBuilder b=new StringBuilder();
  b.append("EPIC 03 FITNESS INTELLIGENCE\nDate: ").append(date).append("\n\nRAW / SYNCED INPUTS\n");
  b.append(metric("Sleep",h==null?null:h.sleepMinutes,"min",h==null?null:h.sleepQuality));b.append(metric("Resting HR",h==null?null:h.restingHeartRate,"bpm",h==null?null:h.restingHeartRateQuality));b.append(metric("Steps",h==null?null:h.steps,"",h==null?null:h.stepsQuality));b.append(metric("Distance",h==null?null:h.distanceKm,"km",h==null?null:h.distanceQuality));b.append(metric("Exercise",h==null?null:h.exerciseMinutes,"min",h==null?null:h.exerciseMinutesQuality));
  b.append("Check-in: ");if(c==null)b.append("missing\n");else b.append("energy=").append(v(c.energy)).append(", fatigue=").append(v(c.muscleFatigue)).append(", motivation=").append(v(c.motivation)).append(", stress=").append(v(c.stress)).append("\n");
  b.append("\nWORKOUTS / TRAINING LOAD\n");if(day.isEmpty())b.append("No workouts for selected day.\n");for(WorkoutEntity w:day)b.append(w.workoutType).append(" ").append(v(w.durationMinutes)).append(" min, RPE=").append(v(w.rpe)).append(w.rpe==null?" (fallback used)":"").append(", load=").append(fmt(calc.workoutLoad(w))).append("\n");b.append("7d load: ").append(fmt(l7)).append("\n28d load: ").append(fmt(l28)).append("\nAcute/chronic ratio: ").append(ratio==null?"missing / insufficient chronic load":fmt(ratio)).append("\n");
  b.append("\nPERSONAL BASELINES\n");for(String m:new String[]{"sleepMinutes","restingHeartRate","steps","distanceKm","trainingLoad"}){b.append(m).append(":\n");for(int window:new int[]{7,28,90}){BaselineEntity x=repo.getBaseline(m,window);b.append("  ").append(window).append("d: ");if(x==null||x.value==null)b.append("missing");else b.append(fmt(x.value)).append(" | samples=").append(x.sampleCount).append(" | confidence=").append(x.confidence);b.append("\n");}}
  b.append("\nRECOVERY\n");if(r==null)b.append("missing — press Recalculate fitness intelligence\n");else{b.append("Score: ").append(r.score==null?"UNKNOWN":r.score).append("\nConfidence: ").append(r.confidence).append("\nRecommendation: ").append(r.recommendation).append("\n");appendComponent(b,"Sleep",r.sleepComponent,.30);appendComponent(b,"Resting HR",r.restingHeartRateComponent,.30);appendComponent(b,"Training load",r.trainingLoadComponent,.25);appendComponent(b,"Subjective",r.subjectiveComponent,.15);appendEffectiveWeights(b,r);}
  return new FitnessDiagnosticsUiState(date,b.toString().trim());}
 private static void appendEffectiveWeights(StringBuilder b,RecoveryEntity r){double sum=0;if(r.sleepComponent!=null)sum+=.30;if(r.restingHeartRateComponent!=null)sum+=.30;if(r.trainingLoadComponent!=null)sum+=.25;if(r.subjectiveComponent!=null)sum+=.15;b.append("Effective weights after missing-data normalization:\n");b.append("  Sleep: ").append(weight(r.sleepComponent,.30,sum)).append("\n  Resting HR: ").append(weight(r.restingHeartRateComponent,.30,sum)).append("\n  Training load: ").append(weight(r.trainingLoadComponent,.25,sum)).append("\n  Subjective: ").append(weight(r.subjectiveComponent,.15,sum)).append("\n");}
 private static String weight(Double component,double raw,double sum){return component==null||sum==0?"missing":fmt(raw/sum*100)+"%";}private static void appendComponent(StringBuilder b,String n,Double v,double w){b.append(n).append(" component: ").append(v==null?"missing":fmt(v)).append(" (configured weight ").append(fmt(w*100)).append("%)\n");}
 private static String metric(String n,Object v,String unit,DomainEnums.DataQuality q){return n+": "+(v==null?"missing":v+(unit.isEmpty()?"":" "+unit))+" | quality="+(q==null?"missing":q)+"\n";}private static String v(Object v){return v==null?"missing":String.valueOf(v);}private static String fmt(double d){return String.format(Locale.ROOT,"%.2f",d);}private static List<WorkoutEntity> between(List<WorkoutEntity>a,LocalDate f,LocalDate t){ZoneId z=ZoneId.systemDefault();Instant s=f.atStartOfDay(z).toInstant(),e=t.plusDays(1).atStartOfDay(z).toInstant();List<WorkoutEntity>o=new ArrayList<>();if(a!=null)for(WorkoutEntity w:a)if(w.startTime!=null&&!w.startTime.isBefore(s)&&w.startTime.isBefore(e))o.add(w);return o;}
}
