package de.fitnesscoach.ui.today;

import java.time.*;import java.util.*;import de.fitnesscoach.data.entity.*;import de.fitnesscoach.data.repository.FitnessCoachRepository;import de.fitnesscoach.domain.fitness.*;import de.fitnesscoach.ui.GermanLabels;

public final class FitnessDiagnosticsMapper {
 private FitnessDiagnosticsMapper(){}
 public static FitnessDiagnosticsUiState map(LocalDate date,FitnessCoachRepository repo){DailyHealthEntity h=repo.getDailyHealth(date);CheckInEntity c=repo.getCheckIn(date);RecoveryEntity r=repo.getRecovery(date);List<WorkoutEntity> all=repo.getWorkouts();TrainingLoadCalculator calc=new DefaultTrainingLoadCalculator();List<WorkoutEntity> day=between(all,date,date);List<WorkoutEntity> w7=between(all,date.minusDays(6),date),w28=between(all,date.minusDays(27),date);double l7=calc.total(w7),l28=calc.total(w28);Double ratio=calc.acuteChronicRatio(l7,l28);StringBuilder b=new StringBuilder();
  b.append("EPIC 03 FITNESS-INTELLIGENZ\nDatum: ").append(date).append("\n\nROH-/SYNCHRONISIERTE EINGABEDATEN\n");
  b.append(metric("Schlaf",h==null?null:h.sleepMinutes,"Min.",h==null?null:h.sleepQuality));b.append(metric("Ruhepuls",h==null?null:h.restingHeartRate,"bpm",h==null?null:h.restingHeartRateQuality));b.append(metric("Schritte",h==null?null:h.steps,"",h==null?null:h.stepsQuality));b.append(metric("Distanz",h==null?null:h.distanceKm,"km",h==null?null:h.distanceQuality));b.append(metric("Training",h==null?null:h.exerciseMinutes,"Min.",h==null?null:h.exerciseMinutesQuality));
  b.append("Check-in: ");if(c==null)b.append("fehlt\n");else b.append("Energie=").append(v(c.energy)).append(", Muskelermüdung=").append(v(c.muscleFatigue)).append(", Motivation=").append(v(c.motivation)).append(", Stress=").append(v(c.stress)).append("\n");
  b.append("\nTRAININGS / TRAININGSLAST\n");if(day.isEmpty())b.append("Keine Trainings für den ausgewählten Tag.\n");for(WorkoutEntity w:day)b.append(GermanLabels.workout(w.workoutType)).append(" ").append(v(w.durationMinutes)).append(" Min., RPE=").append(v(w.rpe)).append(w.rpe==null?" (Fallback verwendet)":"").append(", Last=").append(fmt(calc.workoutLoad(w))).append("\n");b.append("7-Tage-Last: ").append(fmt(l7)).append("\n28-Tage-Last: ").append(fmt(l28)).append("\nAkut/chronisch-Verhältnis: ").append(ratio==null?"fehlt / chronische Last unzureichend":fmt(ratio)).append("\n");
  b.append("\nPERSÖNLICHE BASISWERTE\n");for(String m:new String[]{"sleepMinutes","restingHeartRate","steps","distanceKm","trainingLoad"}){b.append(metricName(m)).append(":\n");for(int window:new int[]{7,28,90}){BaselineEntity x=repo.getBaseline(m,window);b.append("  ").append(window).append(" Tage: ");if(x==null||x.value==null)b.append("fehlt");else b.append(fmt(x.value)).append(" | Stichproben=").append(x.sampleCount).append(" | Vertrauen=").append(GermanLabels.confidence(x.confidence));b.append("\n");}}
  b.append("\nERHOLUNG\n");if(r==null)b.append("fehlt — Fitnessbewertung neu berechnen\n");else{b.append("Score: ").append(r.score==null?"UNBEKANNT":r.score).append("\nVertrauen: ").append(GermanLabels.confidence(r.confidence)).append("\nEmpfehlung: ").append(GermanLabels.recovery(r.recommendation)).append("\n");appendComponent(b,"Schlaf",r.sleepComponent,.30);appendComponent(b,"Ruhepuls",r.restingHeartRateComponent,.30);appendComponent(b,"Trainingslast",r.trainingLoadComponent,.25);appendComponent(b,"Subjektiv",r.subjectiveComponent,.15);appendEffectiveWeights(b,r);}
  return new FitnessDiagnosticsUiState(date,b.toString().trim());}
 private static String metricName(String m){if("sleepMinutes".equals(m))return"Schlaf";if("restingHeartRate".equals(m))return"Ruhepuls";if("steps".equals(m))return"Schritte";if("distanceKm".equals(m))return"Distanz";if("trainingLoad".equals(m))return"Trainingslast";return m;}
 private static void appendEffectiveWeights(StringBuilder b,RecoveryEntity r){double sum=0;if(r.sleepComponent!=null)sum+=.30;if(r.restingHeartRateComponent!=null)sum+=.30;if(r.trainingLoadComponent!=null)sum+=.25;if(r.subjectiveComponent!=null)sum+=.15;b.append("Effektive Gewichtung nach Normalisierung fehlender Daten:\n");b.append("  Schlaf: ").append(weight(r.sleepComponent,.30,sum)).append("\n  Ruhepuls: ").append(weight(r.restingHeartRateComponent,.30,sum)).append("\n  Trainingslast: ").append(weight(r.trainingLoadComponent,.25,sum)).append("\n  Subjektiv: ").append(weight(r.subjectiveComponent,.15,sum)).append("\n");}
 private static String weight(Double component,double raw,double sum){return component==null||sum==0?"fehlt":fmt(raw/sum*100)+"%";}private static void appendComponent(StringBuilder b,String n,Double v,double w){b.append(n).append("-Komponente: ").append(v==null?"fehlt":fmt(v)).append(" (konfigurierte Gewichtung ").append(fmt(w*100)).append("%)\n");}
 private static String metric(String n,Object v,String unit,DomainEnums.DataQuality q){return n+": "+(v==null?"fehlt":v+(unit.isEmpty()?"":" "+unit))+" | Qualität="+(q==null?"fehlt":GermanLabels.quality(q))+"\n";}private static String v(Object v){return v==null?"fehlt":String.valueOf(v);}private static String fmt(double d){return String.format(Locale.GERMANY,"%.2f",d);}private static List<WorkoutEntity> between(List<WorkoutEntity>a,LocalDate f,LocalDate t){ZoneId z=ZoneId.systemDefault();Instant s=f.atStartOfDay(z).toInstant(),e=t.plusDays(1).atStartOfDay(z).toInstant();List<WorkoutEntity>o=new ArrayList<>();if(a!=null)for(WorkoutEntity w:a)if(w.startTime!=null&&!w.startTime.isBefore(s)&&w.startTime.isBefore(e))o.add(w);return o;}
}
