package de.fitnesscoach.ui.today;

import java.time.LocalDate;import java.util.*;import de.fitnesscoach.data.entity.*;import de.fitnesscoach.health.*;import de.fitnesscoach.ui.GermanLabels;

public final class TodayDiagnosticsMapper {
 private TodayDiagnosticsMapper() {}
 public static TodayDiagnosticsUiState map(LocalDate date,DailyHealthEntity health,HealthSyncStateEntity syncState,HealthPermissionSnapshot permissions){List<TodayDiagnosticsUiState.MetricRow> rows=new ArrayList<>();if(health!=null){rows.add(metric("Schritte",health.steps==null?null:String.valueOf(health.steps),health.stepsQuality,permissions,HealthPermissionSpec.STEPS));rows.add(metric("Distanz",health.distanceKm==null?null:String.format(Locale.GERMANY,"%.2f km",health.distanceKm),health.distanceQuality,permissions,HealthPermissionSpec.DISTANCE));rows.add(metric("Aktive Kalorien",health.activeCalories==null?null:health.activeCalories+" kcal",health.activeCaloriesQuality,permissions,HealthPermissionSpec.ACTIVE_CALORIES));rows.add(metric("Schlaf",health.sleepMinutes==null?null:formatMinutes(health.sleepMinutes),health.sleepQuality,permissions,HealthPermissionSpec.SLEEP));rows.add(metric("Ruhepuls",health.restingHeartRate==null?null:String.format(Locale.GERMANY,"%.0f bpm",health.restingHeartRate),health.restingHeartRateQuality,permissions,HealthPermissionSpec.RESTING_HEART_RATE));rows.add(metric("Durchschnittspuls",health.averageHeartRate==null?null:String.format(Locale.GERMANY,"%.0f bpm",health.averageHeartRate),health.averageHeartRateQuality,permissions,HealthPermissionSpec.HEART_RATE));rows.add(metric("Gewicht",health.weightKg==null?null:String.format(Locale.GERMANY,"%.1f kg",health.weightKg),health.weightQuality,permissions,HealthPermissionSpec.WEIGHT));rows.add(metric("Training",health.exerciseMinutes==null?null:formatMinutes(health.exerciseMinutes),health.exerciseMinutesQuality,permissions,HealthPermissionSpec.EXERCISE));}boolean available=permissions!=null&&permissions.isHealthConnectAvailable();String emptyMessage=health==null?"Für diesen Tag liegen keine aggregierten Gesundheitsdaten vor. Synchronisiere Health Connect oder wähle einen importierten Tag.":null;return new TodayDiagnosticsUiState(date,available,health!=null,emptyMessage,rows,syncState==null?null:syncState.lastAttemptAt,syncState==null?null:syncState.lastSuccessfulSyncAt,syncState==null?null:syncState.lastError);}
 private static TodayDiagnosticsUiState.MetricRow metric(String label,String value,DomainEnums.DataQuality quality,HealthPermissionSnapshot permissions,HealthPermissionSpec permission){DomainEnums.DataQuality q=quality==null?DomainEnums.DataQuality.MISSING:quality;return new TodayDiagnosticsUiState.MetricRow(label,value==null?"Nicht verfügbar":value,GermanLabels.quality(q),explanation(q,permissions,permission));}
 private static String explanation(DomainEnums.DataQuality q,HealthPermissionSnapshot permissions,HealthPermissionSpec permission){if(q==DomainEnums.DataQuality.PARTIAL&&permissions!=null&&permissions.getState(permission)!=HealthPermissionSnapshot.State.GRANTED)return"Die Health-Connect-Berechtigung für diesen Wert wurde nicht erteilt.";switch(q){case AVAILABLE:return"Aggregierte Quelldaten sind verfügbar.";case SUSPECT:return"Der Quellwert wirkt unplausibel und wurde markiert, aber nicht verändert.";case PARTIAL:return"Für diesen Wert liegen nur unvollständige Informationen vor.";case MISSING:default:return"Für diesen Tag liegt keine Quellmessung vor.";}}
 private static String formatMinutes(int minutes){int h=minutes/60,r=minutes%60;return h>0?String.format(Locale.GERMANY,"%d Std. %02d Min.",h,r):r+" Min.";}
}
