package de.fitnesscoach.ui.today;

import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import de.fitnesscoach.data.entity.*;import de.fitnesscoach.ui.GermanLabels;

public final class TodayOverviewMapper {
 private TodayOverviewMapper(){}
 public static TodayOverviewUiState map(LocalDate d,DailyHealthEntity h,RecoveryEntity r,BaselineEntity hrBase,List<PlannedWorkoutEntity> planned,HealthSyncStateEntity sync,List<WorkoutEntity> workouts){WorkoutEntity review=null;if(workouts!=null)for(WorkoutEntity w:workouts){if(w.startTime==null)continue;LocalDate wd=w.startTime.atZone(ZoneId.systemDefault()).toLocalDate();if(wd.equals(d)&&w.status==DomainEnums.WorkoutStatus.COMPLETED){review=w;break;}}StringBuilder b=new StringBuilder();b.append("Erholung\n");if(r==null||r.score==null)b.append("Nicht verfügbar\nVertrauen: nicht verfügbar\nEmpfehlung: nicht verfügbar\n");else b.append(r.score).append("/100 · ").append(GermanLabels.recovery(r.recommendation)).append("\nVertrauen: ").append(GermanLabels.confidence(r.confidence)).append("\n");b.append("\nGesundheit\nSchlaf: ").append(h==null||h.sleepMinutes==null?"nicht verfügbar":formatMinutes(h.sleepMinutes)).append("\nRuhepuls: ").append(h==null||h.restingHeartRate==null?"nicht verfügbar":fmt(h.restingHeartRate)+" bpm");if(h!=null&&h.restingHeartRate!=null&&hrBase!=null&&hrBase.value!=null)b.append(" (Δ ").append(signed(h.restingHeartRate-hrBase.value)).append(" bpm gegenüber 28-Tage-Basis)");b.append("\n\nHeutiger Plan\n");if(planned==null||planned.isEmpty())b.append("Kein Training geplant.");else{PlannedWorkoutEntity p=planned.get(0);b.append(p.title==null?GermanLabels.workout(p.workoutType):p.title).append(" · ").append(GermanLabels.workoutStatus(p.status)).append(" · v").append(p.version).append("\nDauer: ").append(p.plannedDurationMinutes==null?"nicht verfügbar":p.plannedDurationMinutes+" min").append("\nDistanz: ").append(p.plannedDistanceKm==null?"nicht verfügbar":fmt(p.plannedDistanceKm)+" km").append("\nPulsziel: ").append(p.targetHeartRateMin==null||p.targetHeartRateMax==null?"nicht verfügbar":fmt(p.targetHeartRateMin)+"–"+fmt(p.targetHeartRateMax)+" bpm").append("\nTempoziel: ").append(p.targetPaceMinSecKm==null||p.targetPaceMaxSecKm==null?"nicht verfügbar":pace(p.targetPaceMinSecKm)+"–"+pace(p.targetPaceMaxSecKm)+" /km").append("\n").append(p.description==null?"":p.description).append("\nBegründung: ").append(reason(r,p));}b.append("\n\nHealth-Sync: ").append(sync==null||sync.lastSuccessfulSyncAt==null?"noch nie":DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm").withZone(ZoneId.systemDefault()).format(sync.lastSuccessfulSyncAt));return new TodayOverviewUiState(d,b.toString(),review==null?null:review.id);}
 private static String reason(RecoveryEntity r,PlannedWorkoutEntity p){if(p.status==DomainEnums.WorkoutStatus.ADAPTED)return"Plan wurde durch die deterministischen Erholungsregeln angepasst.";if(r==null||r.recommendation==null)return"Keine Erholungsbewertung verfügbar; der Plan bleibt konservativ.";return"Deterministische Empfehlung aus der Erholungsbewertung: "+GermanLabels.recovery(r.recommendation)+".";}private static String formatMinutes(int m){return(m/60)+" Std. "+(m%60)+" Min.";}private static String fmt(double v){return String.format(Locale.GERMANY,"%.1f",v);}private static String signed(double v){return(v>=0?"+":"")+fmt(v);}private static String pace(int s){return(s/60)+":"+String.format(Locale.ROOT,"%02d",s%60);}
}
