package de.fitnesscoach.ui.today;

import static org.junit.Assert.*;import java.time.*;import java.util.*;import org.junit.Test;import de.fitnesscoach.data.entity.*;import de.fitnesscoach.data.repository.FitnessCoachRepository;

public class FitnessDiagnosticsMapperTest {
 @Test public void sparseDatasetShowsMissingExplicitly(){FakeRepo r=new FakeRepo();String text=FitnessDiagnosticsMapper.map(LocalDate.of(2026,8,25),r).text;assertTrue(text.contains("Sleep: missing"));assertTrue(text.contains("Check-in: missing"));assertTrue(text.contains("Acute/chronic ratio: missing"));assertTrue(text.contains("RECOVERY\nmissing"));}
 @Test public void completeDatasetShowsBaselinesLoadAndRecovery(){LocalDate d=LocalDate.of(2026,8,25);FakeRepo r=new FakeRepo();r.health=new DailyHealthEntity();r.health.date=d;r.health.sleepMinutes=450;r.health.sleepQuality=DomainEnums.DataQuality.AVAILABLE;r.health.restingHeartRate=55d;r.health.restingHeartRateQuality=DomainEnums.DataQuality.AVAILABLE;r.health.steps=8000L;r.health.stepsQuality=DomainEnums.DataQuality.AVAILABLE;WorkoutEntity w=new WorkoutEntity();w.startTime=d.atTime(8,0).atZone(ZoneId.systemDefault()).toInstant();w.durationMinutes=30;w.rpe=5;w.workoutType=DomainEnums.WorkoutType.EASY;r.workouts.add(w);BaselineEntity b=new BaselineEntity();b.metric="sleepMinutes";b.windowDays=28;b.value=440d;b.sampleCount=25;b.confidence=DomainEnums.Confidence.HIGH;r.baselines.put("sleepMinutes:28",b);r.recovery=new RecoveryEntity();r.recovery.date=d;r.recovery.score=82;r.recovery.confidence=DomainEnums.Confidence.HIGH;r.recovery.recommendation=DomainEnums.RecoveryRecommendation.FULL;r.recovery.sleepComponent=100d;r.recovery.trainingLoadComponent=80d;String text=FitnessDiagnosticsMapper.map(d,r).text;assertTrue(text.contains("load=150.00"));assertTrue(text.contains("28d: 440.00 | samples=25 | confidence=HIGH"));assertTrue(text.contains("Score: 82"));assertTrue(text.contains("Effective weights"));}
 private static final class FakeRepo implements FitnessCoachRepository{DailyHealthEntity health;RecoveryEntity recovery;List<WorkoutEntity>workouts=new ArrayList<>();Map<String,BaselineEntity>baselines=new HashMap<>();public UserProfileEntity getProfile(){return null;}public void saveProfile(UserProfileEntity v){}public List<TrainingAvailabilityEntity>getAvailability(){return Collections.emptyList();}public void saveAvailability(TrainingAvailabilityEntity v){}public GoalEntity getActiveGoal(){return null;}public long insertGoal(GoalEntity v){return 0;}public DailyHealthEntity getDailyHealth(LocalDate d){return health;}public void saveDailyHealth(DailyHealthEntity v){}public List<WorkoutEntity>getWorkouts(){return workouts;}public long insertWorkout(WorkoutEntity v){return 0;}public List<PlannedWorkoutEntity>getPlannedWorkouts(LocalDate f,LocalDate t){return Collections.emptyList();}public long insertPlannedWorkout(PlannedWorkoutEntity v){return 0;}public CheckInEntity getCheckIn(LocalDate d){return null;}public void saveCheckIn(CheckInEntity v){}public BaselineEntity getBaseline(String m,int w){return baselines.get(m+":"+w);}public void saveBaseline(BaselineEntity v){}public RecoveryEntity getRecovery(LocalDate d){return recovery;}public void saveRecovery(RecoveryEntity v){}public List<CoachMemoryEntity>getActiveMemories(){return Collections.emptyList();}public long insertMemory(CoachMemoryEntity v){return 0;}public List<CoachDecisionEntity>getDecisions(){return Collections.emptyList();}public long insertDecision(CoachDecisionEntity v){return 0;}}
}
