package de.fitnesscoach.domain.fitness;

import java.time.Instant;import java.time.LocalDate;import de.fitnesscoach.data.entity.*;

public final class RecoveryCalculator {
 public static final class Config {public final double sleepWeight,rhrWeight,loadWeight,subjectiveWeight;public final int full,normal,reduced,recoveryOnly;public Config(double s,double r,double l,double u,int f,int n,int rd,int ro){sleepWeight=s;rhrWeight=r;loadWeight=l;subjectiveWeight=u;full=f;normal=n;reduced=rd;recoveryOnly=ro;}public static Config defaults(){return new Config(.30,.30,.25,.15,80,65,45,25);}}
 private final Config config; public RecoveryCalculator(){this(Config.defaults());}public RecoveryCalculator(Config config){this.config=config;}
 public RecoveryEntity calculate(LocalDate date,DailyHealthEntity today,BaselineEntity sleepBase,BaselineEntity rhrBase,Double acuteChronic,CheckInEntity checkIn){RecoveryEntity r=new RecoveryEntity();r.date=date;double weighted=0,weights=0;int inputs=0;
  if(today!=null&&today.sleepMinutes!=null&&today.sleepQuality!=DomainEnums.DataQuality.MISSING&&today.sleepQuality!=DomainEnums.DataQuality.SUSPECT&&sleepBase!=null&&sleepBase.value!=null&&sleepBase.value>0){r.sleepComponent=clamp(100d*today.sleepMinutes/sleepBase.value);weighted+=r.sleepComponent*config.sleepWeight;weights+=config.sleepWeight;inputs++;}
  if(today!=null&&today.restingHeartRate!=null&&today.restingHeartRateQuality!=DomainEnums.DataQuality.MISSING&&today.restingHeartRateQuality!=DomainEnums.DataQuality.SUSPECT&&rhrBase!=null&&rhrBase.value!=null&&rhrBase.value>0){double delta=(today.restingHeartRate-rhrBase.value)/rhrBase.value;r.restingHeartRateComponent=clamp(100-delta*300);weighted+=r.restingHeartRateComponent*config.rhrWeight;weights+=config.rhrWeight;inputs++;}
  if(acuteChronic!=null){r.trainingLoadComponent=clamp(100-Math.max(0,acuteChronic-1)*60);weighted+=r.trainingLoadComponent*config.loadWeight;weights+=config.loadWeight;inputs++;}
  if(checkIn!=null){double s=subjective(checkIn);if(!Double.isNaN(s)){r.subjectiveComponent=s;weighted+=s*config.subjectiveWeight;weights+=config.subjectiveWeight;inputs++;}}
  if(weights==0){r.score=null;r.confidence=DomainEnums.Confidence.INSUFFICIENT;r.recommendation=DomainEnums.RecoveryRecommendation.UNKNOWN;}else{r.score=(int)Math.round(clamp(weighted/weights));r.confidence=inputs>=4?DomainEnums.Confidence.HIGH:inputs==3?DomainEnums.Confidence.MEDIUM:inputs==2?DomainEnums.Confidence.LOW:DomainEnums.Confidence.INSUFFICIENT;r.recommendation=recommend(r.score,r.confidence);}r.calculatedAt=Instant.now();return r;}
 private static double subjective(CheckInEntity c){int n=0;double v=0;if(c.energy!=null){v+=scale(c.energy);n++;}if(c.motivation!=null){v+=scale(c.motivation);n++;}if(c.muscleFatigue!=null){v+=100-scale(c.muscleFatigue);n++;}if(c.stress!=null){v+=100-scale(c.stress);n++;}return n==0?Double.NaN:v/n;}
 private static double scale(int v){if(v<1||v>5)throw new IllegalArgumentException("Check-in values must be 1..5");return (v-1)*25d;}private static double clamp(double v){return Math.max(0,Math.min(100,v));}
 private DomainEnums.RecoveryRecommendation recommend(int s,DomainEnums.Confidence c){if(c==DomainEnums.Confidence.INSUFFICIENT)return DomainEnums.RecoveryRecommendation.UNKNOWN;if(s>=config.full)return DomainEnums.RecoveryRecommendation.FULL;if(s>=config.normal)return DomainEnums.RecoveryRecommendation.NORMAL;if(s>=config.reduced)return DomainEnums.RecoveryRecommendation.REDUCED;if(s>=config.recoveryOnly)return DomainEnums.RecoveryRecommendation.RECOVERY_ONLY;return DomainEnums.RecoveryRecommendation.REST;}
}
