package de.fitnesscoach.domain.plan;

import java.time.*;import java.util.*;import de.fitnesscoach.data.entity.*;

public final class TrainingPlanGenerator {
 public static final class Result { public final List<PlannedWorkoutEntity> workouts; public final DomainEnums.Confidence confidence; Result(List<PlannedWorkoutEntity>w,DomainEnums.Confidence c){workouts=w;confidence=c;} }
 public Result generate(LocalDate weekStart,UserProfileEntity profile,GoalEntity goal,List<TrainingAvailabilityEntity> availability,BaselineEntity loadBaseline){Map<Integer,TrainingAvailabilityEntity>a=new HashMap<>();for(TrainingAvailabilityEntity x:availability)a.put(x.dayOfWeek,x);List<LocalDate>days=new ArrayList<>();for(int i=0;i<7;i++){LocalDate d=weekStart.plusDays(i);TrainingAvailabilityEntity x=a.get(d.getDayOfWeek().getValue());if(x!=null&&x.available&&x.maxDurationMinutes!=null&&x.maxDurationMinutes>=20)days.add(d);}List<PlannedWorkoutEntity>out=new ArrayList<>();if(days.isEmpty())return new Result(out,DomainEnums.Confidence.LOW);int sessions=Math.min(days.size(),profile!=null&&profile.fitnessLevel==DomainEnums.FitnessLevel.BEGINNER?3:4);List<DomainEnums.WorkoutType>types=types(sessions,goal);for(int i=0;i<sessions;i++){LocalDate d=days.get((int)Math.floor((double)i*days.size()/sessions));DomainEnums.WorkoutType type=types.get(i);if(i>0&&high(type)&&high(out.get(i-1).workoutType))type=DomainEnums.WorkoutType.EASY;TrainingAvailabilityEntity av=a.get(d.getDayOfWeek().getValue());int base=type==DomainEnums.WorkoutType.LONG?60:type==DomainEnums.WorkoutType.INTERVAL||type==DomainEnums.WorkoutType.TEMPO?40:35;int duration=Math.min(base,av.maxDurationMinutes);PlannedWorkoutEntity p=new PlannedWorkoutEntity();p.date=d;p.sportType=type==DomainEnums.WorkoutType.STRENGTH?DomainEnums.SportType.STRENGTH:DomainEnums.SportType.RUNNING;p.workoutType=type;p.title=title(type);p.description=structure(type,duration);p.plannedDurationMinutes=duration;p.status=DomainEnums.WorkoutStatus.PLANNED;p.version=1;p.createdAt=Instant.now();p.updatedAt=p.createdAt;out.add(p);}DomainEnums.Confidence confidence=loadBaseline!=null&&loadBaseline.confidence!=null&&loadBaseline.confidence!=DomainEnums.Confidence.INSUFFICIENT?loadBaseline.confidence:DomainEnums.Confidence.LOW;return new Result(out,confidence);}
 private List<DomainEnums.WorkoutType>types(int n,GoalEntity g){List<DomainEnums.WorkoutType>x=new ArrayList<>();if(n>=1)x.add(DomainEnums.WorkoutType.EASY);if(n>=2)x.add(DomainEnums.WorkoutType.RECOVERY);if(n>=3)x.add(DomainEnums.WorkoutType.LONG);if(n>=4)x.add(g!=null&&(g.type==DomainEnums.GoalType.RUN_5K_TIME||g.type==DomainEnums.GoalType.RUN_10K_TIME)?DomainEnums.WorkoutType.TEMPO:DomainEnums.WorkoutType.EASY);return x;}private boolean high(DomainEnums.WorkoutType t){return t==DomainEnums.WorkoutType.INTERVAL||t==DomainEnums.WorkoutType.TEMPO||t==DomainEnums.WorkoutType.LONG;}
 private String title(DomainEnums.WorkoutType t){switch(t){case REST:return"Ruhetag";case RECOVERY:return"Regeneration";case EASY:return"Lockerer Lauf";case LONG:return"Langer Lauf";case INTERVAL:return"Intervalltraining";case TEMPO:return"Tempolauf";case STRENGTH:return"Krafttraining";case MOBILITY:return"Mobilität";case CROSS_TRAINING:return"Ausgleichstraining";default:return"Training";}}
 private String mainLabel(DomainEnums.WorkoutType t){switch(t){case RECOVERY:return"sehr locker";case EASY:return"locker";case LONG:return"ruhig und gleichmäßig";case INTERVAL:return"Intervalle";case TEMPO:return"zügiges Tempo";case STRENGTH:return"Kraft";case MOBILITY:return"Mobilität";case CROSS_TRAINING:return"Ausgleichstraining";default:return"locker";}}
 private String structure(DomainEnums.WorkoutType t,int m){if(t==DomainEnums.WorkoutType.REST)return"Ruhetag.";int warm=Math.min(10,Math.max(5,m/5)),cool=warm,main=Math.max(5,m-warm-cool);return"Aufwärmen: "+warm+" Min. locker; Hauptteil: "+main+" Min. "+mainLabel(t)+"; Auslaufen: "+cool+" Min. locker.";}
}
