package de.fitnesscoach.agent;

import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import de.fitnesscoach.BuildConfig;

public class CoachGatewayClient {
 public static final class GatewayException extends Exception{public final int status;public final boolean validation;public GatewayException(int status,boolean validation,String message){super(message);this.status=status;this.validation=validation;}}
 public static final class Reply{public final String type;public final String message;public final List<String>suggestedActions;public final JSONObject memoryCandidate;public final ToolCall toolCall;Reply(String t,String m,List<String>a,JSONObject c,ToolCall tc){type=t;message=m;suggestedActions=a;memoryCandidate=c;toolCall=tc;}}
 public static final class ToolCall{public final String id,name;public final JSONObject arguments;ToolCall(String i,String n,JSONObject a){id=i;name=n;arguments=a;}}
 static String coachEndpoint(String base){return base.replaceAll("/+$","")+"/api/v1/coach";}
 public Reply send(String conversationId,String message,JSONObject context,JSONArray conversation,JSONArray toolResults)throws Exception{String base=BuildConfig.COACH_GATEWAY_URL;if(base==null||base.isBlank())throw new GatewayException(0,false,"Coach-Gateway ist nicht konfiguriert.");URL url=new URL(coachEndpoint(base));HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setConnectTimeout(10000);c.setReadTimeout(45000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json; charset=utf-8");c.setRequestProperty("Accept","application/json");c.setDoOutput(true);JSONObject body=new JSONObject();body.put("conversationId",conversationId);body.put("message",message);body.put("context",context);body.put("conversation",conversation);body.put("toolResults",toolResults);try(OutputStream out=c.getOutputStream()){out.write(body.toString().getBytes(StandardCharsets.UTF_8));}int status=c.getResponseCode();InputStream in=status>=400?c.getErrorStream():c.getInputStream();String raw=in==null?"":new String(in.readAllBytes(),StandardCharsets.UTF_8);return parseResponse(status,raw);}
 public static Reply parseResponse(int status,String raw)throws Exception{if(status>=400){String msg="Coach-Dienst ist nicht verfügbar.";try{JSONObject e=new JSONObject(raw).optJSONObject("error");if(e!=null)msg=e.optString("message",msg);}catch(Exception ignored){}throw new GatewayException(status,status>=400&&status<500,msg);}JSONObject x=new JSONObject(raw);String type=x.getString("type");if("FINAL".equals(type)){List<String>a=new ArrayList<>();JSONArray ja=x.optJSONArray("suggestedActions");if(ja!=null)for(int i=0;i<ja.length();i++)a.add(ja.getString(i));return new Reply(type,x.getString("message"),a,x.optJSONObject("memoryCandidate"),null);}if("TOOL_CALL".equals(type)){JSONObject t=x.getJSONObject("toolCall");String name=t.getString("name");if(!Set.of("get_today_status","get_health_summary","get_training_plan","get_workout_history","get_active_goal","get_baseline","get_progress","modify_workout","reschedule_workout","skip_workout","record_checkin").contains(name))throw new GatewayException(502,false,"Unbekanntes Coach-Tool wurde abgelehnt.");return new Reply(type,null,List.of(),null,new ToolCall(t.getString("id"),name,t.getJSONObject("arguments")));}throw new GatewayException(502,false,"Ungültige Antwort des Coach-Gateways.");}
}
