package de.fitnesscoach.agent;

import org.json.JSONArray;import org.json.JSONObject;import java.time.*;import java.util.*;import de.fitnesscoach.data.entity.*;import de.fitnesscoach.data.repository.FitnessCoachRepository;

public final class CoachContextBuilder {
 private final FitnessCoachRepository repo;public CoachContextBuilder(FitnessCoachRepository repo){this.repo=repo;}
 public JSONObject build(LocalDate date){JSONObject root=new JSONObject();put(root,"profile",profile());put(root,"goal",goal());put(root,"today",today(date));put(root,"recentTraining",recent(date));put(root,"baselines",baselines());put(root,"memories",memories());return root;}
 public String debugSummary(LocalDate date){JSONObject x=build(date);return "Coach-Kontext (allow-list): "+String.join(", ",iterator(x.keys()))+". Rohdaten/Zeitreihen sind ausgeschlossen.";}
 private JSONObject profile(){UserProfileEntity p=repo.getProfile();if(p==null)return unavailable();JSONObject x=new JSONObject();put(x,"fitnessLevel",name(p.fitnessLevel));put(x,"preferredSports",p.preferredSports);put(x,"preferredTrainingTime",p.preferredTrainingTime);put(x,"heightCm",p.heightCm);put(x,"birthYear",p.birthYear);put(x,"availability","available");return x;}
 private JSONObject goal(){GoalEntity g=repo.getActiveGoal();if(g==null)return unavailable();JSONObject x=new JSONObject();put(x,"type",name(g.type));put(x,"title",g.title);put(x,"targetDate",g.targetDate==null?null:g.targetDate.toString());put(x,"targetValue",g.targetValue);put(x,"targetUnit",g.targetUnit);put(x,"startingValue",g.startingValue);put(x,"startingUnit",g.startingUnit);put(x,"availability","available");return x;}
 private JSONObject today(LocalDate d){JSONObject x=new JSONObject();DailyHealthEntity h=repo.getDailyHealth(d);RecoveryEntity r=repo.getRecovery(d);List<PlannedWorkoutEntity> p=repo.getPlannedWorkouts(d,d);if(h==null)put(x,"health",unavailable());else{JSONObject j=new JSONObject();metric(j,"sleepMinutes",h.sleepMinutes,h.sleepQuality);metric(j,"restingHeartRate",h.restingHeartRate,h.restingHeartRateQuality);metric(j,"steps",h.steps,h.stepsQuality);metric(j,"distanceKm",h.distanceKm,h.distanceQuality);metric(j,"exerciseMinutes",h.exerciseMinutes,h.exerciseMinutesQuality);put(x,"health",j);}if(r==null)put(x,"recovery",unavailable());else{JSONObject j=new JSONObject();put(j,"score",r.score);put(j,"confidence",name(r.confidence));put(j,"recommendation",name(r.recommendation));put(j,"availability","available");put(x,"recovery",j);}if(p.isEmpty())put(x,"plannedWorkout",unavailable());else put(x,"plannedWorkout",planned(p.get(0)));CheckInEntity c=repo.getCheckIn(d);if(c==null)put(x,"checkIn",unavailable());else{JSONObject j=new JSONObject();put(j,"energy",c.energy);put(j,"muscleFatigue",c.muscleFatigue);put(j,"motivation",c.motivation);put(j,"stress",c.stress);put(j,"availability","available");put(x,"checkIn",j);}put(x,"date",d.toString());return x;}
 private JSONArray recent(LocalDate d){JSONArray a=new JSONArray();Instant start=d.minusDays(28).atStartOfDay(ZoneId.systemDefault()).toInstant();for(WorkoutEntity w:repo.getWorkouts()){if(w.startTime==null||w.startTime.isBefore(start))continue;JSONObject j=new JSONObject();put(j,"date",w.startTime.atZone(ZoneId.systemDefault()).toLocalDate().toString());put(j,"sportType",name(w.sportType));put(j,"workoutType",name(w.workoutType));put(j,"durationMinutes",w.durationMinutes);put(j,"distanceKm",w.distanceKm);put(j,"rpe",w.rpe);a.put(j);if(a.length()>=20)break;}return a;}
 private JSONObject baselines(){JSONObject x=new JSONObject();for(String m:new String[]{"sleepMinutes","restingHeartRate","steps","distanceKm","trainingLoad"}){JSONObject windows=new JSONObject();for(int w:new int[]{7,28,90}){BaselineEntity b=repo.getBaseline(m,w);JSONObject j=new JSONObject();if(b==null){put(j,"availability","unavailable");}else{put(j,"value",b.value);put(j,"sampleCount",b.sampleCount);put(j,"confidence",name(b.confidence));put(j,"availability","available");}put(windows,String.valueOf(w),j);}put(x,m,windows);}return x;}
 private JSONArray memories(){JSONArray a=new JSONArray();for(CoachMemoryEntity m:repo.getActiveMemories()){JSONObject j=new JSONObject();put(j,"type",name(m.type));put(j,"value",m.value);a.put(j);if(a.length()>=10)break;}return a;}
 private JSONObject planned(PlannedWorkoutEntity p){JSONObject j=new JSONObject();put(j,"id",p.id);put(j,"date",p.date==null?null:p.date.toString());put(j,"sportType",name(p.sportType));put(j,"workoutType",name(p.workoutType));put(j,"title",p.title);put(j,"durationMinutes",p.plannedDurationMinutes);put(j,"distanceKm",p.plannedDistanceKm);put(j,"status",name(p.status));put(j,"version",p.version);put(j,"availability","available");return j;}
 private void metric(JSONObject j,String n,Object value,Object quality){JSONObject m=new JSONObject();if(value==null){put(m,"availability","unavailable");}else{put(m,"value",value);put(m,"availability","available");}put(m,"quality",quality==null?"UNKNOWN":quality.toString());put(j,n,m);}private JSONObject unavailable(){JSONObject j=new JSONObject();put(j,"availability","unavailable");return j;}private String name(Object x){return x==null?null:x.toString();}private static void put(JSONObject j,String k,Object v){j.put(k,v==null?JSONObject.NULL:v);}private static List<String> iterator(Iterator<String> it){List<String>x=new ArrayList<>();while(it.hasNext())x.add(it.next());return x;}
}
