package de.fitnesscoach.ui.coach;

import android.app.Application;import androidx.annotation.NonNull;import androidx.lifecycle.*;import org.json.*;import java.time.LocalDate;import java.util.*;import java.util.concurrent.*;import de.fitnesscoach.agent.*;import de.fitnesscoach.data.db.FitnessCoachDatabase;import de.fitnesscoach.data.repository.*;

public final class CoachViewModel extends AndroidViewModel{
 private final ExecutorService ex=Executors.newSingleThreadExecutor();private final MutableLiveData<CoachUiState>state=new MutableLiveData<>();private final List<CoachMessage>messages=new ArrayList<>();private final String conversationId=UUID.randomUUID().toString();private final CoachContextBuilder contextBuilder;private final AgentToolExecutor tools;private CoachGatewayClient gateway=new CoachGatewayClient();private String pendingMessage;
 public CoachViewModel(@NonNull Application app){super(app);FitnessCoachRepository repo=new RoomFitnessCoachRepository(FitnessCoachDatabase.getInstance(app));contextBuilder=new CoachContextBuilder(repo);tools=new AgentToolExecutor(repo);publish(false,null,false,List.of());}
 public LiveData<CoachUiState>getState(){return state;}void setGatewayForTest(CoachGatewayClient g){gateway=g;}
 public void send(String text){String m=text==null?"":text.trim();if(m.isEmpty()||pendingMessage!=null)return;messages.add(new CoachMessage(true,m));trimMessages();pendingMessage=m;publish(true,null,false,List.of());run(m,false);}
 public void retry(){if(pendingMessage==null)return;publish(true,null,false,List.of());run(pendingMessage,true);}
 private void run(String message,boolean retry){ex.execute(()->{try{JSONArray toolResults=new JSONArray();CoachGatewayClient.Reply reply=null;for(int round=0;round<4;round++){reply=gateway.send(conversationId,message,contextBuilder.build(LocalDate.now()),conversationWithoutCurrent(),toolResults);if("FINAL".equals(reply.type))break;if(reply.toolCall==null)throw new IllegalStateException("Tool-Aufruf fehlt.");JSONObject local=tools.execute(reply.toolCall.name,reply.toolCall.arguments);JSONObject tr=new JSONObject();tr.put("id",reply.toolCall.id);tr.put("name",reply.toolCall.name);tr.put("result",local);toolResults.put(tr);}if(reply==null||!"FINAL".equals(reply.type))throw new IllegalStateException("Zu viele Tool-Runden ohne Abschluss.");messages.add(new CoachMessage(false,reply.message));trimMessages();pendingMessage=null;publish(false,null,false,reply.suggestedActions);}catch(CoachGatewayClient.GatewayException e){publish(false,e.validation?"Die Anfrage wurde vom Gateway abgelehnt. Bitte Eingabe prüfen.":"Coach ist derzeit nicht erreichbar. Du kannst die Anfrage erneut senden.",e.validation,List.of());}catch(Exception e){publish(false,"Coach ist derzeit nicht erreichbar. Du kannst die Anfrage erneut senden.",false,List.of());}});}
 private JSONArray conversationWithoutCurrent() throws JSONException{JSONArray a=new JSONArray();int end=Math.max(0,messages.size()-1),start=Math.max(0,end-8);for(int i=start;i<end;i++){CoachMessage m=messages.get(i);JSONObject j=new JSONObject();j.put("role",m.user?"user":"assistant");j.put("content",m.text);a.put(j);}return a;}
 private void trimMessages(){while(messages.size()>20)messages.remove(0);}private void publish(boolean loading,String error,boolean validation,List<String>actions){state.postValue(new CoachUiState(messages,loading,error,validation,actions,contextBuilder.debugSummary(LocalDate.now())));}@Override protected void onCleared(){ex.shutdownNow();}
}
